defmodule AshPostgres.TestRepo.Migrations.AddHashtagAndHastagAssignment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:post_hashtag_assignments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :resource_id,
        references(:posts,
          column: :id,
          name: "post_hashtag_assignments_resource_id_fkey",
          type: :uuid
        )
      )

      add(:hashtag_id, :uuid)
    end

    create table(:hashtags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:post_hashtag_assignments) do
      modify(
        :hashtag_id,
        references(:hashtags,
          column: :id,
          name: "post_hashtag_assignments_hashtag_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:hashtags) do
      add(:label, :text, null: false)
    end
  end

  def down do
    alter table(:hashtags) do
      remove(:label)
    end

    drop(constraint(:post_hashtag_assignments, "post_hashtag_assignments_hashtag_id_fkey"))

    alter table(:post_hashtag_assignments) do
      modify(:hashtag_id, :uuid)
    end

    drop(table(:hashtags))

    drop(constraint(:post_hashtag_assignments, "post_hashtag_assignments_resource_id_fkey"))

    drop(table(:post_hashtag_assignments))
  end
end
